/* Generated by restful-react */

export const SPEC_VERSION = "1.0.0"; 

export interface GetFirstSecondResponse {[key: string]: any}

export interface GetFirstSecondPathParams {
  /**
   * The first parameter
   */
  first: string;
  /**
   * The second parameter
   */
  second: string
}


export interface DeleteFirstSecondResponse {[key: string]: any}

export interface DeleteFirstSecondPathParams {
  /**
   * The first parameter
   */
  first: string
}

